// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	dto "github.com/saadozone/gin-gorm-rest/internal/dto"
	mock "github.com/stretchr/testify/mock"

	model "github.com/saadozone/gin-gorm-rest/internal/model"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: input
func (_m *UserService) CreateUser(input *dto.RegisterRequestBody) (*model.User, error) {
	ret := _m.Called(input)

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.RegisterRequestBody) (*model.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*dto.RegisterRequestBody) *model.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*dto.RegisterRequestBody) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: input
func (_m *UserService) GetUser(input *dto.UserRequestParams) (*model.User, error) {
	ret := _m.Called(input)

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.UserRequestParams) (*model.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*dto.UserRequestParams) *model.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*dto.UserRequestParams) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserService(t mockConstructorTestingTNewUserService) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
